name: DEPLOY STAGING

on:
  push:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
      -   name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
      -   name: Build with Maven
          run: ./mvnw package -DskipTests=true -Dspring-boot.run.profiles=server

  deploy-server-1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -   name: RUNNING DEPLOY DEVELOPMENT SERVER
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            port: 22
            script: |
              ls
              systemctl status warehouse
              sudo systemctl stop warehouse
              sudo systemctl status warehouse
              echo ================= SERVER 1 STOP APPLICATION SUCCESS =================
              cd warehouse
              ls
              git checkout main
              git pull origin main
              echo ================= SERVER PULL SUCCESS =================
              mvn clean install
              echo INSTALL SUCCESS
              ./mvnw package -DskipTests=true
              echo ================= SERVER BUILD SUCCESS =================
              sudo systemctl start warehouse
              echo ================= START SUCCESS =================
              sudo systemctl status warehouse
              echo ================= SERVER DEPLOYING SUCCESS SERVER 1 =================

